server:
  port: 9004
  servlet:
    context-path: /location


spring:
  application:
      name: location-service
  jackson:
    serialization:
      indent-output: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
